### PR TITLE
Added Xdebug to 7.2 container

### PR DESCRIPTION
**Pull request by elimentz**

### CODE REVIEW

**Comment by veloxy** [comment]
We've left xdebug out at the time of creation due to it slowing down PHP, even when disabled. These type of tools are mostly useful when doing extensive debugging and not much during active development. I don't think we'll be merging this.

Alternatively, we could provide a set of images with xdebug enabled - maybe in a different repo or in this one, eg `7.2-xdebug/`. If we keep it in this repository, the building process may require adjustments as you do not want `7.2-xdebug/` being built before `7.2/`

What are your thoughts @jverdeyen @wesleylancel?

**Comment by elimentz** [comment]
I've been working with xdebug for years and I've never noticed it slowing down my development in any way, shape or form. I think it's a fantastic tool, not only for code coverage but also for debugging and it would be better to include it, I feel. Especially during complex functions, dumps are often not the most ideal debugging tool. However, there probably should be a way to disable it in a production environment

**Comment by veloxy** [comment]
The ci images have xdebug enabled, only the 7.2 version doesn't have it yet (wasn't available at the time) but you could do this pull request there. https://github.com/yappabe/docker-php-ci

**Comment by elimentz** [comment]
But then you still can't run code coverage or debug locally? Doesn't really solve anything in my opinion

**Comment by veloxy** [comment]
You can still run your own images, the performance issues are there and well known, especially on docker.

You could do something like the following:

docker-compose.yml
```yml
services:
    php:
        image: yappabe/php:7.1
```

docker-compose.dev.yml
```yml
services:
    php:
        image: your-own-xdebug-image
```

Then run it `docker-compose -f docker-compose.yml -f docker-compose.dev.yml`

I'll wait for other reviewers to see how/if we want to add xdebug.

**Comment by Trekels** [comment]
I'm in favor of separating this into a different repository, similar to the blackfire repo/image. This seems like a project/personal dependency and should therefore not be included in the base php image as most project wil probably not be using it.

**Comment by elimentz** [comment]
I agree that not every project will need this, but it also seems a bit silly to me to make a separate repository for every specific use case. We have one for blackfire, one for ci, ... Would it not make more sense to have one general build in which we can choose to enable or disable certain features like Blackfire, like Xdebug, like ... using environment variables (or something similar)? So you'd effectively have the same `docker-compose.yml` which loads in parameters from a config file to e.g. enable xdebug on development and disable it on production. I'm not an expert in docker so I have no idea if this is even possible but that would seem so much more efficient than having to make a different repository for each possible configuration.

**Comment by veloxy** [comment]
It is only logical to me that this build, the ci, and Blackfire are split up. The CI contains a host of tools for testing that you don't need in development and would only make the images larger than they need to be. If you'd include all these tools in the development build you'll spend more time downloading them and this isn't a fun thing to be waiting for, for example when your VM just crashed. People also work remotely don't always have the same connection speed as at the office.

That said, my initial argument still stands, and that's the most important one: Xdebug, when installed (even when disabled) slows PHP down. At least it did in the past and still did when I used it recently (though it was on PHP 5.6). If you want to convince me (and possibly others) to add it, show me that it isn't the case (anymore).

To clarify, I'm not against Xdebug - it's a good tool, but not something I have to use day to day so it's not worth it to me personally to have a mostly idle tool sit there, eat up resources, and slow down development whenever it's not being used.

I've already given you a perfectly fine workaround so I don't see the use of turning a simple PHP image into a complex configuration mess as you suggested. If that is even possible, which I doubt. 

If you want to see this merged, you're going to have to come up with a proper solution if you don't like any of the ones that are suggested. Not something you thought out (without any research) and expect us to execute. In the end, you're the one who wants this.

Again, no one is stopping you from making your own Dockerfile that extends these, built for your own specific needs, eg (untested):

```Dockerfile
# etc/docker/php
FROM yappabe/php:7.2
RUN apt-get install -y php-xdebug
ENTRYPOINT ["/bin/bash", "/run.sh"]
```

```yml
# docker-compose.xdebug.yml
...
services:
    php:
        build: etc/docker/php
...
```

Then just start your containers with the custom file `docker-compose up -f docker-compose.xdebug.yml up`.

Also, is there a reason why you removed `php7.2-sqlite`?

I'm always open to suggestions and I still want input from the others, if anyone can come up with actual proof that it doesn't affect performance or has a decent, thought out (proven) solution then I'll gladly vote in favor of adding it. For now, I've said what I wanted to say and will not go further into it unless either of the mentioned conditions are met.

**Comment by elimentz** [comment]
I understand what you mean and I agree with the basic idea of all of it, I'd just use a different approach. I guess I would rather use something (more) similar to the puphpet way of doing things, which is basically a yml file which contains all options (apache2, nginx, xdebug, blackfire,...) that can be enabled or disabled via environment variables, and then build the image on the fly. But hey, that's just me.

I removed sqlite because it prevented my build from succeeding. This is the error I received: 
```bash
The following packages have unmet dependencies: php7.2-sqlite3-dbgsym : 
Depends: php7.2-sqlite3 (= 7.2.7-2+0~20180714182401.1+jessie~1.gbp3fcba8) 
but 7.2.8-1+0~20180725113345.2+jessie~1.gbp571e56 is to be installed 
```
Build details can be found [here](https://hub.docker.com/r/ixudra/docker-php/builds/bboxyv6t2vuyu3xtyuww2wr/). I tried a whole bunch of other things before I removed it, this was the only way I could make it work.

**Comment by StijnRuts** [comment]
> and then build the image on the fly

Prepare for lots of waiting

**Comment by elimentz** [comment]
In the last 8 months, I've had to rebuild my images maybe once or twice.. I think we'll be fine. Or would be, anyways

**Comment by StijnRuts** [comment]
If you only run one or two projects. Not if you have to run 30+

**Comment by wesleylancel** [comment]
Sorry, but as stated above we'll not be merging this because we like to keep this a fairly general Dockerfile. We'll split any debug-specific packages and additions, such as xdebug and Blackfire in separate repositories.

**Pull request closed without merging**
