### PR TITLE
Also install SOAP for PHP7

### PR DESCRIPTION
**Pull request by b-franco**

### CODE REVIEW

**Comment by veloxy** [comment]
I don't like SOAP. But OK

**Comment by jverdeyen** [comment]
We shouldn't work with soap webservices..

**Comment by wesleylancel** [comment]
Too specific for our workflow.

**Comment by jverdeyen** [comment]
We need more args/reasons WHY you need this.

**Comment by veloxy** [comment]
Can you provide some tests and use cases?

**Comment by b-franco** [comment]
I need this because reasons.

**Comment by jverdeyen** [comment]
Good catch @veloxy, we would love to see some tests.

**Comment by jverdeyen** [comment]
@b-franco Merge it yourself, we don't want to be associated with this.

**Pull request merged**
